server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway global Filter
            preLogger: true
            postLogger: true

      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=order-request, order-requests-header2
            - AddResponseHeader=order-response, order-response-header2
            - name: LoggingFilter
              args:
                baseMessage: test
                preLogger: true
                postLogger: true
            - name: CustomFilter
            - RewritePath=/order/(?<segment>.*), /$\{segment}
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/**
#          filters:
#            - AddRequestHeader=user-request, user-requests-header2
#            - AddResponseHeader=user-response, user-response-header2
#            - CustomFilter
#            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/login
            - Method=POST
          filters:
            - AddRequestHeader=user-request, user-requests-header2
            - AddResponseHeader=user-response, user-response-header2
            - CustomFilter
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/users
            - Method=POST
          filters:
            - AddRequestHeader=user-request, user-requests-header2
            - AddResponseHeader=user-response, user-response-header2
            - CustomFilter
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            - Method=GET
          filters:
            - AddRequestHeader=user-request, user-requests-header2
            - AddResponseHeader=user-response, user-response-header2
            - CustomFilter
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
          filters:
            - AddRequestHeader=user-request, user-requests-header2
            - AddResponseHeader=user-response, user-response-header2
            - CustomFilter
            - RewritePath=/catalog/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka